### ISSUE TITLE
Add the ability to set select elements or document it

### ISSUE THREAD

**Issue by davidbgk** [MattiSG/Watai#132]
I tried to do a `this.setFrequencyField(frequency)` with `frequency` being an `option` in a `select` targeted via `select#frequency`. The same pattern works for an `input` or a `textarea` but not for a `select` or I missed something.

**Comment by MattiSG** [comment]
The pattern should be to activate the `option` rather than the `select` itself:

```js
// 1 - Set style feature.js
scenario: [
    TextEditorWidget.boldStyle(),
    // …
]
```

```js
// TextEditorWidget.js
boldStyleOption: '#textEditor select[name="style"] option[value="bold"]',
```

Please let me know if this works  :)

**Comment by davidbgk** [comment]
It works thanks, maybe worth a line in the documentation?

**Comment by MattiSG** [comment]
Could be! Question is: where would you have looked for it? ;)

**Comment by davidbgk** [comment]
Maybe in an advanced example?

**Comment by MattiSG** [comment]
Right, I guess the closest to “recipes” is currently the advanced examples.

Closing this issue, as the problem was solved and the knowledge is properly stored for someone searching for it. It would be an improvement to improve discoverability by adding an example, but this should not be blocking anymore.

**Comment by MattiSG** [comment]
Actually, I just created a [wiki page](https://github.com/MattiSG/Watai/wiki/Recipes) for this  ;)
