### ISSUE TITLE
Minimatch and RegExp DoS issue

### ISSUE THREAD

**Issue by davidbgk** [MattiSG/Watai#205]
Using yarn gave me that warning:

```
warning watai > wd > archiver > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

Might be worth updating `wd` dependency to 1.0?

**Comment by MattiSG** [comment]
Thanks for reporting @davidbgk!

This is a known issue. It is not —at least in my understanding— a real security threat since Watai does not expose any web service.

This update depends on #155, which depended on https://github.com/admc/wd/issues/413 for a long time. It'll indeed be fixed when Watai updates to `wd@1`.

**Comment by davidbgk** [comment]
Alright, let's close it in that case.
